#!/bin/bash
set -e

echo "Installing necessary packages for Ubuntu 24.04..."
sudo apt update
sudo apt -y install realmd libnss-sss libpam-sss sssd sssd-tools adcli samba-common-bin oddjob oddjob-mkhomedir packagekit nfs-common autofs

clear
echo "Attempting to discover Kerberos realms..."
REALM_DISCOVER_OUTPUT=$(realm discover 2>&1)
REALM_DISCOVER_STATUS=$?

if [ $REALM_DISCOVER_STATUS -eq 0 ] && [ -n "$REALM_DISCOVER_OUTPUT" ]; then
    echo "$REALM_DISCOVER_OUTPUT"
    echo "Kerberos realms discovered successfully."
else
    echo "No Kerberos realms were automatically discovered."
    echo "This could be due to DNS configuration issues or because the domain is not properly advertised."
    echo "We'll proceed with manual configuration."
fi

echo "Please enter your domain information:"
read -p "What is the Kerberos realm? (dom.example.com): " REALMAD
read -p "What is the domain controllers short hostname? ('dc' part of dc.dom.example.com): " REALMDC
read -p "What is the domain admin username? " REALMADMIN

# Verify domain controller is reachable
echo "Checking if domain controller is reachable..."
if ping -c 1 $REALMDC.$REALMAD &> /dev/null; then
    echo "Domain controller $REALMDC.$REALMAD is reachable."
else
    echo "Warning: Domain controller $REALMDC.$REALMAD is not reachable."
    echo "This might be a DNS resolution issue."
    
    # Offer to configure DNS
    read -p "Would you like to configure DNS to use the domain controller as a nameserver? (y/n): " configure_dns
    if [[ "$configure_dns" =~ ^[Yy]$ ]]; then
        echo "Configuring DNS to use $REALMDC.$REALMAD as nameserver..."
        
        # Get IP address of domain controller
        read -p "Please enter the IP address of $REALMDC.$REALMAD: " DC_IP
        
        # Backup existing resolv.conf
        sudo cp /etc/resolv.conf /etc/resolv.conf.bak
        
        # Add domain controller as nameserver
        echo "# Generated by univention-domain-join setup script" | sudo tee /etc/resolv.conf
        echo "search $REALMAD" | sudo tee -a /etc/resolv.conf
        echo "nameserver $DC_IP" | sudo tee -a /etc/resolv.conf
        
        # Try ping again
        echo "Testing connection to domain controller again..."
        if ping -c 1 $REALMDC.$REALMAD &> /dev/null; then
            echo "Domain controller $REALMDC.$REALMAD is now reachable."
        else
            echo "Warning: Domain controller $REALMDC.$REALMAD is still not reachable."
            read -p "Do you want to continue anyway? (y/n): " continue_anyway
            if [[ ! "$continue_anyway" =~ ^[Yy]$ ]]; then
                echo "Aborting setup."
                exit 1
            fi
        fi
    else
        read -p "Do you want to continue anyway? (y/n): " continue_anyway
        if [[ ! "$continue_anyway" =~ ^[Yy]$ ]]; then
            echo "Aborting setup."
            exit 1
        fi
    fi
fi
shorthost=${HOSTNAME%%.*}

mkdir -p /etc/univention
echo "Connecting to "$REALMDC.$REALMAD" UCS server and pulling UCS config. Password for domain admin will be prompted."

# Try to connect to UCS server and pull config
if ! ssh -n root@$REALMDC.$REALMAD 'ucr shell | grep -v ^hostname=' >/etc/univention/ucr_master; then
    echo "Error: Failed to connect to UCS server or retrieve UCR variables."
    echo "This could be due to:"
    echo "1. SSH connection issues"
    echo "2. Authentication problems"
    echo "3. The UCS server is not properly configured"
    
    read -p "Do you want to continue with manual configuration? (y/n): " continue_manual
    if [[ "$continue_manual" =~ ^[Yy]$ ]]; then
        echo "Creating minimal UCR master file manually..."
        cat > /etc/univention/ucr_master << EOF
# Manually created UCR master file
ldap_master=$REALMDC.$REALMAD
kerberos_realm=${REALMAD^^}
domainname=$REALMAD
ldap_base=dc=$(echo $REALMAD | sed 's/\./,dc=/g')
ldap_server_name=$REALMDC.$REALMAD
EOF
    else
        echo "Setup cannot continue without UCS configuration. Exiting."
        exit 1
    fi
else
    echo "Successfully retrieved UCR variables from UCS server."
fi

echo "master_ip="$REALMDC.$REALMAD"" >>/etc/univention/ucr_master
chmod 660 /etc/univention/ucr_master

. /etc/univention/ucr_master

# Create an account and save the password
echo "Creating computer account on "$REALMDC.$REALMAD" UCS server. Password for domain admin will be prompted."
password="$(tr -dc A-Za-z0-9_ </dev/urandom | head -c20)"

if ! ssh -n root@$REALMDC.$REALMAD udm computers/linux create \
    --position "cn=computers,${ldap_base}" \
    --set name=$(hostname) --set password="${password}" \
    --set operatingSystem="$(lsb_release -is)" \
    --set operatingSystemVersion="$(lsb_release -rs)"; then
    
    echo "Error: Failed to create computer account on UCS server."
    echo "This could be due to:"
    echo "1. SSH connection issues"
    echo "2. Authentication problems"
    echo "3. The computer account may already exist"
    
    read -p "Do you want to continue anyway? (y/n): " continue_anyway
    if [[ ! "$continue_anyway" =~ ^[Yy]$ ]]; then
        echo "Aborting setup."
        exit 1
    fi
    
    # Ask for a password to use
    echo "Please enter a password to use for the computer account:"
    read -s password
    echo "Password entered manually."
else
    echo "Successfully created computer account on UCS server."
fi

printf '%s' "$password" >/etc/ldap.secret
chmod 0400 /etc/ldap.secret

echo "Performing domain join operation. Password for domain admin will be prompted."
sudo realm join -v -U "$REALMADMIN" "$REALMAD" || {
    echo "Error: Failed to join the realm."
    echo "This could be due to:"
    echo "1. Incorrect domain admin credentials"
    echo "2. DNS configuration issues"
    echo "3. Firewall blocking required ports"
    echo "4. The computer account already exists in the domain"
    
    read -p "Do you want to try an alternative join method? (y/n): " try_alternative
    if [[ "$try_alternative" =~ ^[Yy]$ ]]; then
        echo "Attempting alternative join method..."
        # Alternative method using adcli
        echo "Joining with adcli..."
        echo "Please enter the domain admin password:"
        read -s ADMIN_PASSWORD
        echo "$ADMIN_PASSWORD" | sudo adcli join --domain=$REALMAD --domain-controller=$REALMDC.$REALMAD --login-user=$REALMADMIN --stdin-password
    else
        echo "Domain join failed. Exiting."
        exit 1
    fi
}

# Create ldap.conf
sudo rm -f /etc/ldap/ldap.conf
echo "TLS_CACERT /etc/univention/ssl/ucsCA/CAcert.pem
URI ldap://$ldap_master:7389
BASE $ldap_base" | sudo tee /etc/ldap/ldap.conf

# Configure SSSD to use /nfs/home for home directories
echo "Configuring SSSD to use /nfs/home for home directories..."
sudo mkdir -p /nfs/home

# Check if sssd.conf exists
if [ ! -f /etc/sssd/sssd.conf ]; then
    echo "Warning: /etc/sssd/sssd.conf does not exist. Creating a basic configuration."
    
    # Create directory if it doesn't exist
    sudo mkdir -p /etc/sssd
    
    # Create a basic sssd.conf
    sudo tee /etc/sssd/sssd.conf > /dev/null << EOF
[sssd]
config_file_version = 2
services = nss, pam, sudo
domains = ${REALMAD^^}

[nss]
reconnection_retries = 3

[pam]
reconnection_retries = 3

[domain/${REALMAD^^}]
auth_provider = krb5
krb5_realm = ${REALMAD^^}
krb5_server = $REALMDC.$REALMAD
id_provider = ldap
ldap_uri = ldap://$REALMDC.$REALMAD:7389
ldap_search_base = $ldap_base
ldap_tls_reqcert = never
cache_credentials = true
enumerate = true
override_homedir = /nfs/home/%u
EOF
    
    # Set proper permissions
    sudo chmod 600 /etc/sssd/sssd.conf
else
    # Backup the original sssd.conf
    sudo cp /etc/sssd/sssd.conf /etc/sssd/sssd.conf.bak
    
    # Check if the domain section exists
    if grep -q '\[domain\/' /etc/sssd/sssd.conf; then
        # Modify sssd.conf to use /nfs/home
        sudo sed -i '/\[domain\/.*\]/a override_homedir = /nfs/home/%u' /etc/sssd/sssd.conf
        
        # Check if the modification was successful
        if ! grep -q 'override_homedir = /nfs/home/%u' /etc/sssd/sssd.conf; then
            echo "Warning: Failed to add override_homedir to sssd.conf using sed."
            echo "Adding it manually to the end of the file."
            
            # Get the domain name from sssd.conf
            DOMAIN_SECTION=$(grep -o '\[domain\/[^]]*\]' /etc/sssd/sssd.conf | head -1)
            
            if [ -n "$DOMAIN_SECTION" ]; then
                # Add the override_homedir line to the domain section
                sudo sed -i "/$DOMAIN_SECTION/a override_homedir = /nfs/home/%u" /etc/sssd/sssd.conf
            else
                # Append to the end of the file
                echo "override_homedir = /nfs/home/%u" | sudo tee -a /etc/sssd/sssd.conf > /dev/null
            fi
        fi
    else
        echo "Warning: No domain section found in sssd.conf."
        echo "Adding a domain section with override_homedir."
        
        # Append a domain section to the end of the file
        sudo tee -a /etc/sssd/sssd.conf > /dev/null << EOF

[domain/${REALMAD^^}]
auth_provider = krb5
krb5_realm = ${REALMAD^^}
krb5_server = $REALMDC.$REALMAD
id_provider = ldap
ldap_uri = ldap://$REALMDC.$REALMAD:7389
ldap_search_base = $ldap_base
ldap_tls_reqcert = never
cache_credentials = true
enumerate = true
override_homedir = /nfs/home/%u
EOF
        
        # Update the domains line in the sssd section
        if grep -q '^\[sssd\]' /etc/sssd/sssd.conf; then
            # Check if there's already a domains line
            if grep -q 'domains = ' /etc/sssd/sssd.conf; then
                # Append our domain to the existing domains line
                sudo sed -i "/domains = /s/$/, ${REALMAD^^}/" /etc/sssd/sssd.conf
            else
                # Add a domains line after the sssd section
                sudo sed -i "/^\[sssd\]/a domains = ${REALMAD^^}" /etc/sssd/sssd.conf
            fi
        else
            # Add an sssd section if it doesn't exist
            sudo tee -a /etc/sssd/sssd.conf > /dev/null << EOF

[sssd]
config_file_version = 2
services = nss, pam, sudo
domains = ${REALMAD^^}
EOF
        fi
    fi
fi

# Ensure proper permissions
sudo chmod 600 /etc/sssd/sssd.conf

# Configure autofs for NFS home directories
echo "Configuring autofs for NFS home directories..."
sudo tee /etc/auto.master.d/home.autofs > /dev/null << EOF
/nfs/home /etc/auto.home --timeout=60
EOF

sudo tee /etc/auto.home > /dev/null << EOF
* $REALMDC.$REALMAD:/home/&
EOF

# Ensure autofs is enabled and started
sudo systemctl enable autofs
sudo systemctl restart autofs

# Configure PAM for home directory creation
echo "Activating mkhomedir module..."
echo 'Name: activate mkhomedir
Default: yes
Priority: 900
Session-Type: Additional
Session:
        required  pam_mkhomedir.so umask=0022 skel=/etc/skel' | sudo tee /usr/share/pam-configs/mkhomedir
sudo pam-auth-update --enable mkhomedir

# Restart SSSD
sudo systemctl restart sssd

echo "Domain join completed successfully with home directories mapped to /nfs/home"
echo "Note: Ensure that the NFS server on $REALMDC.$REALMAD is properly configured to export /home"

# Prompt for reboot
read -r -p "UCS Domain Join Complete! REBOOT NOW? [y/N] " rebootnow
if [[ "$rebootnow" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
    echo "Rebooting!"
    sudo reboot
else
    read -p "Reboot not selected. Press any key to finish with script."
fi
